package models;

public enum Feature {


    SMART_PARKING,
    STRCTURAL_HEALTH,
    NOISE,
    SMARTPHONE_DECTECTION,
    ELETRONMAGENTIC_FIELD_LEVELS,
    TRAFFIC_CONGESTION,
    SMART_LIGHTING,
    WASTE_MANAG,
    SMART_ROAD,
    WASTE_MANAGEMENT,
}
